# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, homeWindow):
        homeWindow.setObjectName("homeWindow")
        homeWindow.resize(350, 276)
        font = QtGui.QFont()
        font.setPointSize(8)
        homeWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(homeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(100, 90, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.versionLabel = QtWidgets.QLabel(self.centralwidget)
        self.versionLabel.setGeometry(QtCore.QRect(90, 120, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.versionLabel.setFont(font)
        self.versionLabel.setObjectName("versionLabel")
        homeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(homeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 24))
        self.menubar.setStyleSheet("QMenuBar {\n"
"    background-color: #F0F0F0;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background: transparent;\n"
"    padding: 4px 8px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background: #3498db; /* Set the background color when hovered */\n"
"    color: white; /* Set the text color when hovered */\n"
"}\n"
"")
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setTearOffEnabled(False)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuCompatibility = QtWidgets.QMenu(self.menubar)
        self.menuCompatibility.setObjectName("menuCompatibility")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        homeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(homeWindow)
        self.statusbar.setObjectName("statusbar")
        homeWindow.setStatusBar(self.statusbar)
        self.actionLoadRom = QtWidgets.QAction(homeWindow)
        self.actionLoadRom.setObjectName("actionLoadRom")
        self.actionView = QtWidgets.QAction(homeWindow)
        self.actionView.setObjectName("actionView")
        self.actionModify = QtWidgets.QAction(homeWindow)
        self.actionModify.setObjectName("actionModify")
        self.actionVisit_Original_Repo = QtWidgets.QAction(homeWindow)
        self.actionVisit_Original_Repo.setObjectName("actionVisit_Original_Repo")
        self.actionVisit_this_wrapper_s_repo = QtWidgets.QAction(homeWindow)
        self.actionVisit_this_wrapper_s_repo.setObjectName("actionVisit_this_wrapper_s_repo")
        self.menuFile.addAction(self.actionLoadRom)
        self.menuSettings.addAction(self.actionModify)
        self.menuCompatibility.addAction(self.actionView)
        self.menuAbout.addAction(self.actionVisit_Original_Repo)
        self.menuAbout.addAction(self.actionVisit_this_wrapper_s_repo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuCompatibility.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(homeWindow)
        QtCore.QMetaObject.connectSlotsByName(homeWindow)

    def retranslateUi(self, homeWindow):
        _translate = QtCore.QCoreApplication.translate
        homeWindow.setWindowTitle(_translate("homeWindow", "Panda3DS GUI (Panda3DS 0.4)"))
        self.titleLabel.setText(_translate("homeWindow", "Panda3ds GUI"))
        self.versionLabel.setText(_translate("homeWindow", "Running Panda3ds 0.4-beta"))
        self.menuFile.setTitle(_translate("homeWindow", "File"))
        self.menuSettings.setTitle(_translate("homeWindow", "Settings"))
        self.menuCompatibility.setTitle(_translate("homeWindow", "Compatibility Spreadsheet "))
        self.menuAbout.setTitle(_translate("homeWindow", "About"))
        self.actionLoadRom.setText(_translate("homeWindow", "Load ROM..."))
        self.actionView.setText(_translate("homeWindow", "View"))
        self.actionModify.setText(_translate("homeWindow", "Modify"))
        self.actionVisit_Original_Repo.setText(_translate("homeWindow", "Visit Original Repo..."))
        self.actionVisit_this_wrapper_s_repo.setText(_translate("homeWindow", "Visit this wrapper\'s repo"))
