# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settingsMenu(object):
    def setupUi(self, settingsMenu):
        settingsMenu.setObjectName("settingsMenu")
        settingsMenu.resize(474, 416)
        self.centralwidget = QtWidgets.QWidget(settingsMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(200, 20, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.GeneralSettingsLabel = QtWidgets.QLabel(self.centralwidget)
        self.GeneralSettingsLabel.setGeometry(QtCore.QRect(60, 111, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GeneralSettingsLabel.setFont(font)
        self.GeneralSettingsLabel.setObjectName("GeneralSettingsLabel")
        self.discordRpcCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.discordRpcCheckBox.setGeometry(QtCore.QRect(60, 130, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.discordRpcCheckBox.setFont(font)
        self.discordRpcCheckBox.setObjectName("discordRpcCheckBox")
        self.GPUSettingsLabel = QtWidgets.QLabel(self.centralwidget)
        self.GPUSettingsLabel.setGeometry(QtCore.QRect(60, 151, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GPUSettingsLabel.setFont(font)
        self.GPUSettingsLabel.setObjectName("GPUSettingsLabel")
        self.shaderJitCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.shaderJitCheckBox.setGeometry(QtCore.QRect(60, 170, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.shaderJitCheckBox.setFont(font)
        self.shaderJitCheckBox.setChecked(True)
        self.shaderJitCheckBox.setObjectName("shaderJitCheckBox")
        self.rendererOptionLabel = QtWidgets.QLabel(self.centralwidget)
        self.rendererOptionLabel.setGeometry(QtCore.QRect(60, 60, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.rendererOptionLabel.setFont(font)
        self.rendererOptionLabel.setObjectName("rendererOptionLabel")
        self.batterySettingsLabel = QtWidgets.QLabel(self.centralwidget)
        self.batterySettingsLabel.setGeometry(QtCore.QRect(60, 191, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.batterySettingsLabel.setFont(font)
        self.batterySettingsLabel.setObjectName("batterySettingsLabel")
        self.chargerPluggedCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.chargerPluggedCheckBox.setGeometry(QtCore.QRect(60, 210, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.chargerPluggedCheckBox.setFont(font)
        self.chargerPluggedCheckBox.setChecked(True)
        self.chargerPluggedCheckBox.setObjectName("chargerPluggedCheckBox")
        self.batteryPercentageLabel = QtWidgets.QLabel(self.centralwidget)
        self.batteryPercentageLabel.setGeometry(
            QtCore.QRect(190, 210, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.batteryPercentageLabel.setFont(font)
        self.batteryPercentageLabel.setObjectName("batteryPercentageLabel")
        self.percentageLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.percentageLineEdit.setGeometry(QtCore.QRect(300, 210, 31, 20))
        self.percentageLineEdit.setObjectName("percentageLineEdit")
        self.SDSettingsLabel = QtWidgets.QLabel(self.centralwidget)
        self.SDSettingsLabel.setGeometry(QtCore.QRect(60, 230, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SDSettingsLabel.setFont(font)
        self.SDSettingsLabel.setObjectName("SDSettingsLabel")
        self.virtualSDCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.virtualSDCheckBox.setGeometry(QtCore.QRect(60, 250, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.virtualSDCheckBox.setFont(font)
        self.virtualSDCheckBox.setChecked(True)
        self.virtualSDCheckBox.setObjectName("virtualSDCheckBox")
        self.readOnlySdCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.readOnlySdCheckBox.setGeometry(QtCore.QRect(60, 270, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.readOnlySdCheckBox.setFont(font)
        self.readOnlySdCheckBox.setChecked(False)
        self.readOnlySdCheckBox.setObjectName("readOnlySdCheckBox")
        self.OKButton = QtWidgets.QPushButton(self.centralwidget)
        self.OKButton.setGeometry(QtCore.QRect(390, 350, 75, 23))
        self.OKButton.setObjectName("OKButton")
        settingsMenu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(settingsMenu)
        self.statusbar.setObjectName("statusbar")
        settingsMenu.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(settingsMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 474, 21))
        self.menubar.setObjectName("menubar")
        settingsMenu.setMenuBar(self.menubar)

        self.retranslateUi(settingsMenu)
        QtCore.QMetaObject.connectSlotsByName(settingsMenu)

    def retranslateUi(self, settingsMenu):
        _translate = QtCore.QCoreApplication.translate
        settingsMenu.setWindowTitle(_translate(
            "settingsMenu", "Panda3DS GUI - Settings"))
        self.titleLabel.setText(_translate("settingsMenu", "Settings"))
        self.GeneralSettingsLabel.setText(
            _translate("settingsMenu", "General"))
        self.discordRpcCheckBox.setText(
            _translate("settingsMenu", "Enable Discord RPC"))
        self.GPUSettingsLabel.setText(_translate("settingsMenu", "GPU"))
        self.shaderJitCheckBox.setText(
            _translate("settingsMenu", "Enable Shader JIT"))
        self.rendererOptionLabel.setText(_translate("settingsMenu", "NOTE: In the CLI version, you can use an unfinished Vulkan implementation.\n"
                                                    "This version is aimed at more casual users, so I emitted it from this menu."))
        self.batterySettingsLabel.setText(
            _translate("settingsMenu", "Battery"))
        self.chargerPluggedCheckBox.setText(
            _translate("settingsMenu", "Charger Plugged?"))
        self.batteryPercentageLabel.setText(
            _translate("settingsMenu", "Battery Percentage:"))
        self.percentageLineEdit.setText(_translate("settingsMenu", "3"))
        self.SDSettingsLabel.setText(_translate("settingsMenu", "SD"))
        self.virtualSDCheckBox.setText(
            _translate("settingsMenu", "Use Virtual SD?"))
        self.readOnlySdCheckBox.setText(
            _translate("settingsMenu", "SD Card Read Only?"))
        self.OKButton.setText(_translate("settingsMenu", "OK"))
