
[General]
EnableDiscordRPC = true

[GPU]
EnableShaderJIT = true
Renderer = "opengl"

[Battery]
ChargerPlugged = true
BatteryPercentage = 12

[SD]
UseVirtualSD = true
WriteProtectVirtualSD = false

[GUI]
ShowConsole = true
saveConsoleToLog = false

